name: apptawthra
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  easy_localization: ^2.1.0
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  firebase_storage:
  firebase_core: ^0.5.1
  firebase_auth: ^0.18.4+1
  cloud_firestore:
  flushbar: ^1.10.4
  google_fonts: ^1.1.1
  animated_text_kit:
  cached_network_image: ^2.4.1
  image_picker: ^0.6.7+21
  dio: ^3.0.10
  loading_overlay: ^0.2.1
  webview_flutter: ^0.3.24
  firebase_admob:
  logger:
  flutter_svg:
  flutter_staggered_grid_view: ^0.3.2
  #translator: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
    - lang/en-US.json
    - lang/ar-DZ.json
